// "use client";

// import type { AnalysisResult } from "@/lib/types";

// export function Dashboard({
//   result,
// }: {
//   result: AnalysisResult;
// }) {
//   const input = result.input;

//   return (
//     <div className="space-y-5">

//       {/* =========================
//           SHIPMENT SUMMARY
//       ========================= */}
//       <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

//         <div className="mb-5">
//           <h2 className="text-lg font-semibold">
//             Shipment Overview
//           </h2>

//           <p className="text-xs text-muted mt-1">
//             Shipment information used for the risk analysis.
//           </p>
//         </div>

//         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">

//           {/* PRODUCT */}
//           <div className="rounded-xl border border-border bg-panel-2 p-4">
//             <div className="text-[10px] mono uppercase tracking-wide text-muted">
//               Product
//             </div>

//             <div className="text-sm font-medium mt-2">
//               {input.product}
//             </div>
//           </div>

//           {/* ORIGIN */}
//           <div className="rounded-xl border border-border bg-panel-2 p-4">
//             <div className="text-[10px] mono uppercase tracking-wide text-muted">
//               Origin
//             </div>

//             <div className="text-sm font-medium mt-2">
//               {input.origin_city}
//             </div>

//             <div className="text-xs text-muted mt-0.5">
//               {input.origin_province}
//             </div>
//           </div>

//           {/* DESTINATION */}
//           <div className="rounded-xl border border-border bg-panel-2 p-4">
//             <div className="text-[10px] mono uppercase tracking-wide text-muted">
//               Destination
//             </div>

//             <div className="text-sm font-medium mt-2">
//               {input.destination_city}
//             </div>

//             <div className="text-xs text-muted mt-0.5">
//               {input.destination_province}
//             </div>
//           </div>

//           {/* SHIPPING MODE */}
//           <div className="rounded-xl border border-border bg-panel-2 p-4">
//             <div className="text-[10px] mono uppercase tracking-wide text-muted">
//               Shipping Mode
//             </div>

//             <div className="text-sm font-medium mt-2">
//               {input.shippingMode || "Not specified"}
//             </div>
//           </div>

//         </div>
//       </section>

//       {/* =========================
//           RISK RESULT
//       ========================= */}
//       <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

//         <div className="mb-5">
//           <h2 className="text-lg font-semibold">
//             Risk Assessment
//           </h2>

//           <p className="text-xs text-muted mt-1">
//             Overall assessment generated by the intelligence pipeline.
//           </p>
//         </div>

//         <div className="rounded-xl border border-border bg-panel-2 p-6 text-center">

//           <div className="text-[10px] mono uppercase tracking-wide text-muted">
//             Overall Risk
//           </div>

//           <div className="text-3xl font-bold text-accent mt-2">
//             {String(
//               (result as unknown as { overallRisk?: unknown })
//                 .overallRisk ?? "N/A"
//             )}
//           </div>

//         </div>
//       </section>

//       {/* =========================
//           RAW RESULT
//       ========================= */}
//       <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

//         <div className="mb-4">
//           <h2 className="text-lg font-semibold">
//             Analysis Data
//           </h2>

//           <p className="text-xs text-muted mt-1">
//             Raw result returned by the analysis pipeline.
//           </p>
//         </div>

//         <pre className="overflow-x-auto rounded-xl bg-panel-2 border border-border p-4 text-xs mono text-muted">
//           {JSON.stringify(result, null, 2)}
//         </pre>

//       </section>

//     </div>
//   );
// }


"use client";

import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  CheckCircle2,
  Clock3,
  Fuel,
  Gauge,
  MapPin,
  Package,
  Route,
  ShieldAlert,
  Ship,
  Truck,
  Waves,
  Zap,
} from "lucide-react";

import type {
  AnalysisResult,
  AnalyzeEvent,
  DependencyDriver,
  RiskFactor,
  RouteOption,
} from "@/lib/types";

interface DashboardProps {
  result: AnalysisResult | null;
  events?: AnalyzeEvent[];
  loading?: boolean;
}

function riskLabel(score: number) {
  if (score >= 75) return "High Risk";
  if (score >= 50) return "Moderate Risk";
  return "Low Risk";
}

function riskTone(score: number) {
  if (score >= 75) {
    return {
      text: "text-red-600",
      bg: "bg-red-50",
      border: "border-red-200",
      bar: "bg-red-500",
    };
  }

  if (score >= 50) {
    return {
      text: "text-amber-600",
      bg: "bg-amber-50",
      border: "border-amber-200",
      bar: "bg-amber-500",
    };
  }

  return {
    text: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    bar: "bg-emerald-500",
  };
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
}

function categoryLabel(category: string) {
  const labels: Record<string, string> = {
    commodity: "Commodity",
    freight: "Freight",
    port: "Port",
    weather: "Weather",
    geopolitical: "Regional",
    supplier: "Supplier",
    regulatory: "Regulatory",
  };

  return labels[category] ?? category;
}

function DriverIcon({ name }: { name: string }) {
  const value = name.toLowerCase();

  if (value.includes("freight") || value.includes("transport")) {
    return <Truck className="h-4 w-4" />;
  }

  if (value.includes("port")) {
    return <Ship className="h-4 w-4" />;
  }

  if (value.includes("fuel") || value.includes("oil")) {
    return <Fuel className="h-4 w-4" />;
  }

  if (value.includes("weather")) {
    return <Waves className="h-4 w-4" />;
  }

  if (value.includes("compliance")) {
    return <ShieldAlert className="h-4 w-4" />;
  }

  return <Package className="h-4 w-4" />;
}

function RiskCard({ factor }: { factor: RiskFactor }) {
  const tone = riskTone(factor.score);

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
            {categoryLabel(factor.category)}
          </p>

          <h3 className="mt-1 text-sm font-semibold text-slate-900">
            {factor.label}
          </h3>
        </div>

        <div className={`rounded-xl px-3 py-2 ${tone.bg}`}>
          <span className={`text-lg font-bold ${tone.text}`}>
            {factor.score}
          </span>
          <span className={`ml-1 text-xs ${tone.text}`}>/100</span>
        </div>
      </div>

      <div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100">
        <div
          className={`h-full rounded-full ${tone.bar}`}
          style={{ width: `${Math.min(100, Math.max(0, factor.score))}%` }}
        />
      </div>

      <p className="mt-4 text-sm leading-6 text-slate-600">
        {factor.detail}
      </p>

      <div className="mt-4 rounded-xl bg-slate-50 p-3">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
          Recommended action
        </p>

        <p className="mt-1 text-sm font-medium leading-5 text-slate-800">
          {factor.actionable}
        </p>
      </div>

      {factor.keyFindings?.length > 0 && (
        <div className="mt-4 space-y-2">
          {factor.keyFindings.slice(0, 3).map((finding, index) => (
            <div
              key={`${finding}-${index}`}
              className="flex gap-2 text-xs text-slate-500"
            >
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
              <span>{finding}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function RouteCard({
  route,
  selected,
}: {
  route: RouteOption;
  selected: boolean;
}) {
  const method = route.method.toLowerCase();

  const Icon =
    method.includes("truck")
      ? Truck
      : method.includes("air")
        ? Zap
        : method.includes("rail")
          ? Route
          : Ship;

  return (
    <div
      className={`rounded-2xl border p-5 ${
        selected
          ? "border-slate-900 bg-slate-900 text-white"
          : "border-slate-200 bg-white"
      }`}
    >
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <div
            className={`rounded-xl p-2 ${
              selected ? "bg-white/10" : "bg-slate-100"
            }`}
          >
            <Icon
              className={`h-5 w-5 ${
                selected ? "text-white" : "text-slate-700"
              }`}
            />
          </div>

          <div>
            <p
              className={`text-sm font-semibold ${
                selected ? "text-white" : "text-slate-900"
              }`}
            >
              {route.method}
            </p>

            {selected && (
              <p className="mt-0.5 text-xs text-slate-300">
                Recommended route
              </p>
            )}
          </div>
        </div>

        {selected && (
          <CheckCircle2 className="h-5 w-5 text-emerald-400" />
        )}
      </div>

      <div className="mt-5 grid grid-cols-2 gap-4">
        <div>
          <p
            className={`text-xs ${
              selected ? "text-slate-400" : "text-slate-400"
            }`}
          >
            Estimated cost
          </p>

          <p
            className={`mt-1 text-lg font-bold ${
              selected ? "text-white" : "text-slate-900"
            }`}
          >
            {formatCurrency(route.cost)}
          </p>
        </div>

        <div>
          <p
            className={`text-xs ${
              selected ? "text-slate-400" : "text-slate-400"
            }`}
          >
            Transit
          </p>

          <p
            className={`mt-1 text-lg font-bold ${
              selected ? "text-white" : "text-slate-900"
            }`}
          >
            {route.transitDays} days
          </p>
        </div>
      </div>

      <p
        className={`mt-4 text-sm leading-5 ${
          selected ? "text-slate-300" : "text-slate-500"
        }`}
      >
        {route.note}
      </p>
    </div>
  );
}

function DriverCard({ driver }: { driver: DependencyDriver }) {
  const isUp = driver.trend === "up";
  const isDown = driver.trend === "down";

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-slate-100 p-2 text-slate-600">
            <DriverIcon name={driver.name} />
          </div>

          <div>
            <p className="text-sm font-semibold text-slate-900">
              {driver.name}
            </p>

            <p className="text-xs text-slate-400">
              {driver.unit}
            </p>
          </div>
        </div>

        <div
          className={`flex items-center gap-1 text-xs font-semibold ${
            isUp
              ? "text-red-500"
              : isDown
                ? "text-emerald-600"
                : "text-slate-400"
          }`}
        >
          {isUp && <ArrowUp className="h-3.5 w-3.5" />}
          {isDown && <ArrowDown className="h-3.5 w-3.5" />}
          {driver.changePct > 0 ? "+" : ""}
          {driver.changePct}%
        </div>
      </div>

      <div className="mt-4 flex items-end justify-between">
        <div>
          <p className="text-2xl font-bold text-slate-900">
            {driver.current.toLocaleString("id-ID")}
          </p>

          <p className="mt-1 text-xs text-slate-400">
            {driver.priceLive ? "Live data" : "Estimated / fallback"}
          </p>
        </div>

        <span
          className={`rounded-full px-2.5 py-1 text-xs font-medium ${
            driver.impact === "high"
              ? "bg-red-50 text-red-600"
              : driver.impact === "medium"
                ? "bg-amber-50 text-amber-600"
                : "bg-slate-100 text-slate-500"
          }`}
        >
          {driver.impact} impact
        </span>
      </div>

      <p className="mt-3 text-xs leading-5 text-slate-500">
        Affects: {driver.affects}
      </p>
    </div>
  );
}

export default function Dashboard({
  result,
  events = [],
  loading = false,
}: DashboardProps) {
  if (!result) {
    return (
      <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center">
        <Gauge className="mx-auto h-10 w-10 text-slate-300" />

        <h2 className="mt-4 text-lg font-semibold text-slate-900">
          No analysis yet
        </h2>

        <p className="mx-auto mt-2 max-w-md text-sm text-slate-500">
          Enter an Indonesian shipment in the analysis form to generate
          supply-chain risk intelligence.
        </p>
      </div>
    );
  }

  const tone = riskTone(result.riskScore);

  const recommendedRoute =
    result.routes.find((route) => route.recommended) ??
    result.routes[0];

  const topRisks = [...result.riskFactors]
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  const latestForecast =
    result.costForecasts[result.costForecasts.length - 1];

  const highAlerts = result.alerts.filter(
    (alert) => alert.severity === "high",
  );

  return (
    <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl space-y-6">
        {/* Header */}
        <section className="rounded-3xl bg-slate-950 p-6 text-white shadow-sm sm:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
                <span>WayFinder</span>
                <span>·</span>
                <span>Indonesia Supply Chain Intelligence</span>
              </div>

              <h1 className="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">
                {result.input.product}
              </h1>

              <div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-slate-300">
                <span>{result.input.origin_city}</span>
                <span className="text-slate-500">→</span>
                <span>{result.input.destination_city}</span>
              </div>
            </div>

            <div className="flex flex-wrap gap-2 text-xs">
              <span className="rounded-full bg-white/10 px-3 py-1.5 text-slate-300">
                Domestic Indonesia
              </span>

              <span className="rounded-full bg-white/10 px-3 py-1.5 text-slate-300">
                {result.dataMode === "live"
                  ? "Live intelligence"
                  : "Fallback data"}
              </span>

              <span className="rounded-full bg-white/10 px-3 py-1.5 text-slate-300">
                {result.input.shipDate}
              </span>
            </div>
          </div>
        </section>

        {/* KPI row */}
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                Overall Risk
              </p>

              <Gauge className={`h-5 w-5 ${tone.text}`} />
            </div>

            <div className="mt-3 flex items-end gap-2">
              <span className={`text-4xl font-bold ${tone.text}`}>
                {result.riskScore}
              </span>

              <span className="mb-1 text-sm text-slate-400">
                / 100
              </span>
            </div>

            <p className={`mt-1 text-sm font-medium ${tone.text}`}>
              {riskLabel(result.riskScore)}
            </p>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                Cost Outlook
              </p>

              <ArrowUp className="h-5 w-5 text-red-500" />
            </div>

            <p className="mt-3 text-3xl font-bold text-slate-900">
              +{result.expectedCostIncreasePct}%
            </p>

            <p className="mt-1 text-sm text-slate-500">
              expected logistics cost increase
            </p>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                Delay Outlook
              </p>

              <Clock3 className="h-5 w-5 text-amber-500" />
            </div>

            <p className="mt-3 text-3xl font-bold text-slate-900">
              {result.expectedDelayDays[0]}–{result.expectedDelayDays[1]}
            </p>

            <p className="mt-1 text-sm text-slate-500">
              additional days expected
            </p>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                Shipment
              </p>

              <Package className="h-5 w-5 text-slate-500" />
            </div>

            <p className="mt-3 text-3xl font-bold text-slate-900">
              {result.input.weightKg.toLocaleString("id-ID")}
            </p>

            <p className="mt-1 text-sm text-slate-500">
              kg
              {result.input.quantity
                ? ` · ${result.input.quantity.toLocaleString("id-ID")} units`
                : ""}
            </p>
          </div>
        </section>

        {/* Executive summary + top risks */}
        <section className="grid gap-6 lg:grid-cols-[1.3fr_0.7fr]">
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-slate-700" />

              <h2 className="text-lg font-semibold text-slate-900">
                Executive Summary
              </h2>
            </div>

            <p className="mt-4 text-sm leading-7 text-slate-600">
              {result.executiveSummary}
            </p>

            <div className="mt-6 grid gap-3 sm:grid-cols-3">
              {topRisks.map((risk) => {
                const riskToneValue = riskTone(risk.score);

                return (
                  <div
                    key={`${risk.category}-${risk.label}`}
                    className={`rounded-xl border p-4 ${riskToneValue.border} ${riskToneValue.bg}`}
                  >
                    <p className="text-xs font-medium uppercase tracking-wide text-slate-400">
                      {categoryLabel(risk.category)}
                    </p>

                    <p
                      className={`mt-1 text-sm font-semibold ${riskToneValue.text}`}
                    >
                      {risk.score}/100
                    </p>

                    <p className="mt-1 text-xs leading-5 text-slate-600">
                      {risk.label}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-amber-500" />

                <h2 className="text-lg font-semibold text-slate-900">
                  Alerts
                </h2>
              </div>

              <span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-600">
                {highAlerts.length} high
              </span>
            </div>

            <div className="mt-5 space-y-3">
              {result.alerts.length === 0 ? (
                <div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">
                  No major alerts detected for this shipment.
                </div>
              ) : (
                result.alerts.slice(0, 4).map((alert, index) => (
                  <div
                    key={`${alert.title}-${index}`}
                    className="rounded-xl border border-slate-100 bg-slate-50 p-4"
                  >
                    <div className="flex items-start gap-3">
                      <div
                        className={`mt-0.5 h-2 w-2 shrink-0 rounded-full ${
                          alert.severity === "high"
                            ? "bg-red-500"
                            : alert.severity === "medium"
                              ? "bg-amber-500"
                              : "bg-slate-400"
                        }`}
                      />

                      <div>
                        <p className="text-sm font-semibold text-slate-800">
                          {alert.title}
                        </p>

                        <p className="mt-1 text-xs leading-5 text-slate-500">
                          {alert.impact}
                        </p>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </section>

        {/* Risk factors */}
        <section>
          <div className="mb-4 flex items-end justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Risk Intelligence
              </p>

              <h2 className="mt-1 text-xl font-bold text-slate-900">
                Risk Factors
              </h2>
            </div>

            <span className="text-sm text-slate-400">
              {result.riskFactors.length} factors analyzed
            </span>
          </div>

          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {result.riskFactors.map((factor) => (
              <RiskCard
                key={`${factor.category}-${factor.label}`}
                factor={factor}
              />
            ))}
          </div>
        </section>

        {/* Cost forecast */}
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Forecast
              </p>

              <h2 className="mt-1 text-xl font-bold text-slate-900">
                Cost Pressure Outlook
              </h2>
            </div>

            {latestForecast && (
              <p className="text-sm text-slate-500">
                {latestForecast.horizonDays}-day horizon
              </p>
            )}
          </div>

          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[600px] text-left">
              <thead>
                <tr className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400">
                  <th className="pb-3 font-semibold">Horizon</th>
                  <th className="pb-3 font-semibold">Product</th>
                  <th className="pb-3 font-semibold">Freight</th>
                  <th className="pb-3 font-semibold">Total logistics</th>
                </tr>
              </thead>

              <tbody>
                {result.costForecasts.map((forecast) => (
                  <tr
                    key={forecast.horizonDays}
                    className="border-b border-slate-50 last:border-0"
                  >
                    <td className="py-4 text-sm font-semibold text-slate-800">
                      {forecast.horizonDays} days
                    </td>

                    <td className="py-4 text-sm text-slate-600">
                      +{forecast.productCostPct}%
                    </td>

                    <td className="py-4 text-sm text-slate-600">
                      +{forecast.freightCostPct}%
                    </td>

                    <td className="py-4 text-sm font-semibold text-red-600">
                      +{forecast.landedCostPct}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Drivers */}
        <section>
          <div className="mb-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Dependency Intelligence
            </p>

            <h2 className="mt-1 text-xl font-bold text-slate-900">
              Supply Chain Drivers
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Key factors affecting material, freight, and domestic logistics
              costs.
            </p>
          </div>

          {result.drivers.length === 0 ? (
            <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">
              No dependency drivers available.
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {result.drivers.map((driver) => (
                <DriverCard
                  key={`${driver.name}-${driver.unit}`}
                  driver={driver}
                />
              ))}
            </div>
          )}
        </section>

        {/* Routes */}
        <section>
          <div className="mb-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Domestic Transportation
            </p>

            <h2 className="mt-1 text-xl font-bold text-slate-900">
              Route Options
            </h2>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            {result.routes.map((route) => (
              <RouteCard
                key={`${route.method}-${route.transitDays}`}
                route={route}
                selected={route === recommendedRoute}
              />
            ))}
          </div>
        </section>

        {/* Port recommendation - NO MAP */}
        {result.portRecommendation && (
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-slate-700" />

                  <h2 className="text-xl font-bold text-slate-900">
                    Port Recommendation
                  </h2>
                </div>

                <p className="mt-2 text-sm leading-6 text-slate-500">
                  {result.portRecommendation.rationale}
                </p>
              </div>

              <div className="rounded-xl bg-emerald-50 px-4 py-3">
                <p className="text-xs font-medium text-emerald-600">
                  Recommended
                </p>

                <p className="mt-1 text-sm font-bold text-emerald-700">
                  {result.portRecommendation.recommended}
                </p>
              </div>
            </div>

            <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              {result.portRecommendation.options.map((port) => (
                <div
                  key={port.name}
                  className={`rounded-xl border p-4 ${
                    port.name === result.portRecommendation?.recommended
                      ? "border-emerald-200 bg-emerald-50"
                      : "border-slate-200 bg-slate-50"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-slate-900">
                        {port.name}
                      </p>

                      {port.name ===
                        result.portRecommendation?.recommended && (
                        <span className="mt-1 inline-block text-xs font-medium text-emerald-600">
                          Recommended option
                        </span>
                      )}
                    </div>

                    <span className="text-xs font-semibold text-slate-500">
                      {port.congestionScore}/100 congestion
                    </span>
                  </div>

                  <div className="mt-4 grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-xs text-slate-400">
                        Wait time
                      </p>

                      <p className="mt-1 text-sm font-semibold text-slate-800">
                        {port.waitDays} days
                      </p>
                    </div>

                    <div>
                      <p className="text-xs text-slate-400">
                        Freight estimate
                      </p>

                      <p className="mt-1 text-sm font-semibold text-slate-800">
                        {formatCurrency(port.freightCost)}
                      </p>
                    </div>
                  </div>

                  <p className="mt-3 text-xs leading-5 text-slate-500">
                    {port.note}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Action plan */}
        <section>
          <div className="mb-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Decision Support
            </p>

            <h2 className="mt-1 text-xl font-bold text-slate-900">
              Action Plan
            </h2>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="divide-y divide-slate-100">
              {result.actionPlan.map((item, index) => (
                <div
                  key={`${item.action}-${index}`}
                  className="flex gap-4 p-5"
                >
                  <div
                    className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${
                      item.urgency === "high"
                        ? "bg-red-50 text-red-600"
                        : item.urgency === "medium"
                          ? "bg-amber-50 text-amber-600"
                          : "bg-slate-100 text-slate-600"
                    }`}
                  >
                    {index + 1}
                  </div>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                      <div>
                        <p className="text-sm font-semibold text-slate-900">
                          {item.action}
                        </p>

                        <p className="mt-1 text-sm leading-5 text-slate-500">
                          {item.why}
                        </p>
                      </div>

                      <span
                        className={`w-fit shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${
                          item.urgency === "high"
                            ? "bg-red-50 text-red-600"
                            : item.urgency === "medium"
                              ? "bg-amber-50 text-amber-600"
                              : "bg-slate-100 text-slate-500"
                        }`}
                      >
                        {item.urgency}
                      </span>
                    </div>

                    <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-400">
                      <span>{categoryLabel(item.category)}</span>

                      <span>·</span>

                      <span>{item.deadline}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Recommendations */}
        {result.recommendations.length > 0 && (
          <section>
            <div className="mb-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Recommendations
              </p>

              <h2 className="mt-1 text-xl font-bold text-slate-900">
                What to do next
              </h2>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {result.recommendations.map((recommendation, index) => (
                <div
                  key={`${recommendation.action}-${index}`}
                  className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"
                >
                  <div className="flex gap-3">
                    <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-500" />

                    <div>
                      <p className="text-sm font-semibold text-slate-900">
                        {recommendation.action}
                      </p>

                      <p className="mt-2 text-sm leading-6 text-slate-500">
                        {recommendation.rationale}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Data transparency */}
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="text-sm font-semibold text-slate-900">
                Intelligence Sources
              </h2>

              <p className="mt-1 text-xs text-slate-500">
                {result.searches.length} web searches executed during analysis.
              </p>
            </div>

            <span
              className={`w-fit rounded-full px-3 py-1 text-xs font-medium ${
                result.dataMode === "live"
                  ? "bg-emerald-50 text-emerald-600"
                  : "bg-amber-50 text-amber-600"
              }`}
            >
              {result.dataMode === "live"
                ? "Live Bright Data"
                : "Mock / fallback"}
            </span>
          </div>

          {result.searches.length > 0 && (
            <div className="mt-5 grid gap-2 sm:grid-cols-2">
              {result.searches.slice(0, 8).map((search, index) => (
                <div
                  key={`${search.query}-${index}`}
                  className="rounded-xl bg-slate-50 p-3"
                >
                  <p className="text-xs font-medium text-slate-700">
                    {search.agent}
                  </p>

                  <p className="mt-1 line-clamp-2 text-xs text-slate-400">
                    {search.query}
                  </p>

                  <p className="mt-1 text-[11px] text-slate-400">
                    {search.results} results · {search.mode}
                  </p>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Analysis status */}
        {loading && events.length > 0 && (
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="flex items-center gap-2">
              <div className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />

              <h2 className="text-sm font-semibold text-slate-900">
                Analysis in progress
              </h2>
            </div>

            <div className="mt-4 space-y-2">
              {events
                .filter((event) => event.type === "agent")
                .slice(-8)
                .map((event, index) => {
                  if (event.type !== "agent") return null;

                  return (
                    <div
                      key={`${event.id}-${index}`}
                      className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"
                    >
                      <span className="text-xs text-slate-600">
                        {event.name}
                      </span>

                      <span
                        className={`text-xs font-medium ${
                          event.status === "done"
                            ? "text-emerald-600"
                            : event.status === "error"
                              ? "text-red-600"
                              : "text-amber-600"
                        }`}
                      >
                        {event.status}
                      </span>
                    </div>
                  );
                })}
            </div>
          </section>
        )}

        <p className="pb-4 text-center text-xs text-slate-400">
          Generated {new Date(result.generatedAt).toLocaleString("id-ID")}
          {" · "}
          WayFinder Indonesia Supply Chain Intelligence
        </p>
      </div>
    </main>
  );
}
