"use client";

import type { AnalysisResult } from "@/lib/types";

export function Dashboard({
  result,
}: {
  result: AnalysisResult;
}) {
  const input = result.input;

  return (
    <div className="space-y-5">

      {/* =========================
          SHIPMENT SUMMARY
      ========================= */}
      <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

        <div className="mb-5">
          <h2 className="text-lg font-semibold">
            Shipment Overview
          </h2>

          <p className="text-xs text-muted mt-1">
            Shipment information used for the risk analysis.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">

          {/* PRODUCT */}
          <div className="rounded-xl border border-border bg-panel-2 p-4">
            <div className="text-[10px] mono uppercase tracking-wide text-muted">
              Product
            </div>

            <div className="text-sm font-medium mt-2">
              {input.product}
            </div>
          </div>

          {/* ORIGIN */}
          <div className="rounded-xl border border-border bg-panel-2 p-4">
            <div className="text-[10px] mono uppercase tracking-wide text-muted">
              Origin
            </div>

            <div className="text-sm font-medium mt-2">
              {input.origin_city}
            </div>

            <div className="text-xs text-muted mt-0.5">
              {input.origin_province}
            </div>
          </div>

          {/* DESTINATION */}
          <div className="rounded-xl border border-border bg-panel-2 p-4">
            <div className="text-[10px] mono uppercase tracking-wide text-muted">
              Destination
            </div>

            <div className="text-sm font-medium mt-2">
              {input.destination_city}
            </div>

            <div className="text-xs text-muted mt-0.5">
              {input.destination_province}
            </div>
          </div>

          {/* SHIPPING MODE */}
          <div className="rounded-xl border border-border bg-panel-2 p-4">
            <div className="text-[10px] mono uppercase tracking-wide text-muted">
              Shipping Mode
            </div>

            <div className="text-sm font-medium mt-2">
              {input.shippingMode || "Not specified"}
            </div>
          </div>

        </div>
      </section>

      {/* =========================
          RISK RESULT
      ========================= */}
      <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

        <div className="mb-5">
          <h2 className="text-lg font-semibold">
            Risk Assessment
          </h2>

          <p className="text-xs text-muted mt-1">
            Overall assessment generated by the intelligence pipeline.
          </p>
        </div>

        <div className="rounded-xl border border-border bg-panel-2 p-6 text-center">

          <div className="text-[10px] mono uppercase tracking-wide text-muted">
            Overall Risk
          </div>

          <div className="text-3xl font-bold text-accent mt-2">
            {String(
              (result as unknown as { overallRisk?: unknown })
                .overallRisk ?? "N/A"
            )}
          </div>

        </div>
      </section>

      {/* =========================
          RAW RESULT
      ========================= */}
      <section className="rounded-2xl border border-border bg-panel/70 p-5 sm:p-6">

        <div className="mb-4">
          <h2 className="text-lg font-semibold">
            Analysis Data
          </h2>

          <p className="text-xs text-muted mt-1">
            Raw result returned by the analysis pipeline.
          </p>
        </div>

        <pre className="overflow-x-auto rounded-xl bg-panel-2 border border-border p-4 text-xs mono text-muted">
          {JSON.stringify(result, null, 2)}
        </pre>

      </section>

    </div>
  );
}