export const Province = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Kepulauan Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "DKI Jakarta",
  "Jawa Barat",
  "Banten",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
];

export const Cities: Record<string, string[]> = {
  Aceh: [
    "Banda Aceh",
    "Lhokseumawe",
    "Langsa",
    "Sabang",
    "Subulussalam",
    "Aceh Besar",
    "Aceh Barat",
    "Aceh Utara",
  ],

  "Sumatera Utara": [
    "Medan",
    "Binjai",
    "Pematangsiantar",
    "Tanjungbalai",
    "Sibolga",
    "Tebing Tinggi",
    "Deli Serdang",
    "Karo",
    "Langkat",
  ],

  "Sumatera Barat": [
    "Padang",
    "Bukittinggi",
    "Padang Panjang",
    "Pariaman",
    "Payakumbuh",
    "Sawahlunto",
    "Solok",
    "Agam",
  ],

  Riau: [
    "Pekanbaru",
    "Dumai",
    "Bengkalis",
    "Siak",
    "Kampar",
    "Pelalawan",
    "Rokan Hilir",
    "Indragiri Hilir",
  ],

  "Kepulauan Riau": [
    "Batam",
    "Tanjungpinang",
    "Bintan",
    "Karimun",
    "Natuna",
    "Lingga",
  ],

  Jambi: [
    "Jambi",
    "Sungai Penuh",
    "Batanghari",
    "Bungo",
    "Kerinci",
    "Merangin",
    "Muaro Jambi",
  ],

  "Sumatera Selatan": [
    "Palembang",
    "Lubuklinggau",
    "Pagar Alam",
    "Prabumulih",
    "Banyuasin",
    "Muara Enim",
    "Musi Banyuasin",
    "Ogan Ilir",
  ],

  "Kepulauan Bangka Belitung": [
    "Pangkalpinang",
    "Bangka",
    "Belitung",
    "Bangka Tengah",
    "Bangka Barat",
    "Bangka Selatan",
  ],

  Bengkulu: [
    "Bengkulu",
    "Bengkulu Selatan",
    "Bengkulu Tengah",
    "Bengkulu Utara",
    "Kaur",
    "Kepahiang",
    "Lebong",
  ],

  Lampung: [
    "Bandar Lampung",
    "Metro",
    "Lampung Selatan",
    "Lampung Tengah",
    "Lampung Timur",
    "Lampung Utara",
    "Pesawaran",
    "Pringsewu",
  ],

  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Jakarta Barat",
    "Kepulauan Seribu",
  ],

  "Jawa Barat": [
    "Bandung",
    "Bekasi",
    "Bogor",
    "Depok",
    "Cimahi",
    "Cirebon",
    "Sukabumi",
    "Tasikmalaya",
    "Banjar",
    "Garut",
    "Karawang",
    "Purwakarta",
    "Subang",
    "Indramayu",
    "Cianjur",
    "Sumedang",
  ],

  Banten: [
    "Serang",
    "Cilegon",
    "Tangerang",
    "Tangerang Selatan",
    "Pandeglang",
    "Lebak",
  ],

  "Jawa Tengah": [
    "Semarang",
    "Surakarta",
    "Magelang",
    "Pekalongan",
    "Salatiga",
    "Tegal",
    "Cilacap",
    "Jepara",
    "Kudus",
    "Purworejo",
    "Kebumen",
    "Banyumas",
    "Boyolali",
    "Klaten",
    "Sukoharjo",
    "Wonogiri",
  ],

  "DI Yogyakarta": [
    "Yogyakarta",
    "Sleman",
    "Bantul",
    "Kulon Progo",
    "Gunungkidul",
  ],

  "Jawa Timur": [
    "Surabaya",
    "Malang",
    "Batu",
    "Kediri",
    "Blitar",
    "Madiun",
    "Mojokerto",
    "Pasuruan",
    "Probolinggo",
    "Banyuwangi",
    "Jember",
    "Sidoarjo",
    "Gresik",
    "Lamongan",
    "Tuban",
    "Bojonegoro",
  ],

  Bali: [
    "Denpasar",
    "Badung",
    "Gianyar",
    "Tabanan",
    "Bangli",
    "Buleleng",
    "Karangasem",
    "Klungkung",
    "Jembrana",
  ],

  "Nusa Tenggara Barat": [
    "Mataram",
    "Bima",
    "Dompu",
    "Lombok Barat",
    "Lombok Tengah",
    "Lombok Timur",
    "Sumbawa",
  ],

  "Nusa Tenggara Timur": [
    "Kupang",
    "Ende",
    "Maumere",
    "Labuan Bajo",
    "Waingapu",
    "Timor Tengah Selatan",
  ],

  "Kalimantan Barat": [
    "Pontianak",
    "Singkawang",
    "Kubu Raya",
    "Mempawah",
    "Sintang",
    "Ketapang",
    "Sambas",
  ],

  "Kalimantan Tengah": [
    "Palangka Raya",
    "Sampit",
    "Pangkalan Bun",
    "Kapuas",
    "Barito Selatan",
    "Barito Utara",
  ],

  "Kalimantan Selatan": [
    "Banjarmasin",
    "Banjarbaru",
    "Banjar",
    "Tanah Laut",
    "Barito Kuala",
    "Kotabaru",
    "Tabalong",
  ],

  "Kalimantan Timur": [
    "Samarinda",
    "Balikpapan",
    "Bontang",
    "Kutai Kartanegara",
    "Kutai Timur",
    "Berau",
    "Penajam Paser Utara",
  ],

  "Kalimantan Utara": [
    "Tarakan",
    "Tanjung Selor",
    "Nunukan",
    "Malinau",
    "Bulungan",
  ],

  "Sulawesi Utara": [
    "Manado",
    "Bitung",
    "Tomohon",
    "Kotamobagu",
    "Minahasa",
    "Minahasa Utara",
  ],

  "Sulawesi Tengah": [
    "Palu",
    "Donggala",
    "Poso",
    "Toli-Toli",
    "Morowali",
    "Banggai",
  ],

  "Sulawesi Selatan": [
    "Makassar",
    "Parepare",
    "Palopo",
    "Gowa",
    "Maros",
    "Bone",
    "Bulukumba",
    "Wajo",
    "Sidenreng Rappang",
  ],

  "Sulawesi Tenggara": [
    "Kendari",
    "Baubau",
    "Kolaka",
    "Konawe",
    "Muna",
    "Wakatobi",
  ],

  Gorontalo: [
    "Gorontalo",
    "Bone Bolango",
    "Gorontalo Utara",
    "Boalemo",
    "Pohuwato",
  ],

  "Sulawesi Barat": [
    "Mamuju",
    "Majene",
    "Polewali Mandar",
    "Mamasa",
    "Pasangkayu",
  ],

  Maluku: [
    "Ambon",
    "Tual",
    "Maluku Tengah",
    "Buru",
    "Seram Bagian Barat",
  ],

  "Maluku Utara": [
    "Ternate",
    "Tidore Kepulauan",
    "Halmahera Barat",
    "Halmahera Selatan",
    "Halmahera Utara",
  ],

  Papua: [
    "Jayapura",
    "Merauke",
    "Biak Numfor",
    "Keerom",
    "Sarmi",
    "Mimika",
  ],

  "Papua Barat": [
    "Manokwari",
    "Sorong",
    "Fakfak",
    "Kaimana",
    "Teluk Bintuni",
    "Teluk Wondama",
  ],
};